### ISSUE TITLE
Update Style In Form Step 2  

### ISSUE THREAD

**Issue by angelik0828** [Azordev/search-by-time-github#7]
### Explanation
This container will be centered and will have a small form, there will be two fields, one that allows you to choose before, after, the same, in the next field a calendar window will appear that allows you to choose the date, two buttons centered at the bottom of the form, button centered on the form on the left.

### Screenshots
![image](https://user-images.githubusercontent.com/4030477/155407377-e0627e4d-fa8b-434b-afe8-3cace645e689.png)
![image](https://user-images.githubusercontent.com/4030477/155407736-67d7009d-8325-4db3-a1b8-1bdf7cb674a2.png)

### Checklist

 - [ ] The 2px border container, color `#C4C4C4`, will have a maximum width of 526X388.
 - [ ] 1px border color `#C4C4C4` font color `#000000` font type: Montserrat plain text field, which allows you to choose between three options, After, Before, Equal To.
 - [ ] A field with the date will be a calendar format.
 - [ ]   Buttons centered at the bottom colored `#001E66` and `#76A4FF` according to design.
 - [ ] Back button or left centered circular button of color `#001E66` with centered arrow.
### References
(https://www.figma.com/file/Pw5EfnvCLnXox2mFS40kdW/Azordev?node-id=0%3A1)

**Comment by ygamboalh** [comment]
I want to be assigned to this task
